// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Task API",
    "version": "1"
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "Health check",
        "description": "Check if the API is running",
        "operationId": "api.get./health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "API is healthy"
          }
        }
      }
    },
    "/tasks": {
      "get": {
        "summary": "Get all tasks",
        "description": "Retrieve all tasks from the database",
        "operationId": "api.get./tasks",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "List of all tasks"
          },
          "500": {
            "description": "Could not retrieve tasks"
          }
        }
      },
      "post": {
        "summary": "Create a new task",
        "description": "Create a new task with a title",
        "operationId": "api.post./tasks",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateTaskRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Task created successfully"
          },
          "400": {
            "description": "Invalid input - title must be a string"
          },
          "500": {
            "description": "Could not create task"
          }
        }
      }
    },
    "/tasks/{taskId}": {
      "get": {
        "summary": "Get a task by ID",
        "description": "Retrieve a specific task by its ID",
        "operationId": "api.get./tasks/{taskId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "taskId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Task found"
          },
          "404": {
            "description": "Task not found"
          },
          "500": {
            "description": "Could not retrieve task"
          }
        }
      },
      "put": {
        "summary": "Update a task",
        "description": "Update an existing task's title or completed status",
        "operationId": "api.put./tasks/{taskId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateTaskRequest"
            }
          },
          {
            "name": "taskId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Task updated successfully"
          },
          "400": {
            "description": "Invalid input"
          },
          "500": {
            "description": "Could not update task"
          }
        }
      },
      "delete": {
        "summary": "Delete a task",
        "description": "Delete a task by its ID",
        "operationId": "api.delete./tasks/{taskId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "taskId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Task deleted successfully"
          },
          "400": {
            "description": "Task ID is required"
          },
          "500": {
            "description": "Could not delete task"
          }
        }
      }
    }
  },
  "definitions": {
    "CreateTaskRequest": {
      "properties": {
        "title": {
          "title": "CreateTaskRequest.title",
          "type": "string"
        }
      },
      "required": [
        "title"
      ],
      "additionalProperties": false,
      "title": "CreateTaskRequest",
      "type": "object"
    },
    "UpdateTaskRequest": {
      "properties": {
        "title": {
          "title": "UpdateTaskRequest.title",
          "type": "string"
        },
        "completed": {
          "title": "UpdateTaskRequest.completed",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "title": "UpdateTaskRequest",
      "type": "object"
    },
    "TaskResponse": {
      "properties": {
        "taskId": {
          "title": "TaskResponse.taskId",
          "type": "string"
        },
        "title": {
          "title": "TaskResponse.title",
          "type": "string"
        },
        "completed": {
          "title": "TaskResponse.completed",
          "type": "boolean"
        },
        "createdAt": {
          "title": "TaskResponse.createdAt",
          "type": "string"
        }
      },
      "required": [
        "taskId",
        "title",
        "completed",
        "createdAt"
      ],
      "additionalProperties": false,
      "title": "TaskResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};